### PR TITLE
Java Tensor I/O RFC

### PR DESCRIPTION
**Pull request by karllessard**

### CODE REVIEW

**Comment by saudet** [comment]
Before going into the details, we should get the basics right tough. This API relies heavily on Java arrays and buffers, which are limited to Integer.MAX_VALUE elements. For example, a 3D tensor with 1000x2000x2000 dimensions reaches that, so it's not uncommon. I think that would be important to get right, first.

**Comment by karllessard** [comment]
The NdArray API "supports" Java arrays but does not "rely" on them.
`NdArray` interface returns 64-bit integers as the possible number of elements
and you can also feed them using streams, for example. I left deliberately
the indices as 32-bit ints because it would be surprising to see tensors
with a single dimension exceeding Integer.MAX_VALUE elements.

Now if you were referring to the implementation class snippets I left
there, to be honest they were a last-minute addition and I mistakenly uses
arrays there. The same problem also applies with tensors implementation if
they work with a single ByteBuffer.

But like I mention in the document, those implementation snippets should
not be granted as a solution part of the proposal but just to help
understanding the role of each classes. Now I see I should probably just
remove them since they can lead to confusion or open useless debate on the
code details at this point. I'll make an update but it would be great if
you can continue your review focusing more on the `NdArray` APIs and the
hierarchy of objects at a high-level. If we can all agree on those basis
first, we can then discuss about the implementation details.

**Comment by Craigacp** [comment]
Does NdArrayIterator extend java.util.Iterator? If not, then I think it would be useful to do so (even though the standard next() will impose a boxing cost) and change the hasMoreElements to a standard hasNext call. It can still use the specialised get() call, but adding a boxing next() call will make things easier. It'll make interop with the rest of the JVM ecosystem better e.g. it'll let you wrap it in a Scala iterator to make Scala language features work better.

**Comment by karllessard** [comment]
@Craigacp , I removed the implementation code snippets and replace them by few class diagrams, into which `NdArrayIterator` now implement `java.util.Iterator`. 

Yes, the reason for not doing it before was to avoid the use of autoboxing but, as for the `NdArray`, we can compare the performances later and decide then if we should stick to primitive types or not.

**Comment by saudet** [comment]
> The NdArray API "supports" Java arrays but does not "rely" on them. `NdArray` interface returns 64-bit integers as the possible number of elements and you can also feed them using streams, for example. I left deliberately the indices as 32-bit ints because it would be surprising to see tensors with a single dimension exceeding Integer.MAX_VALUE elements.

That would not be surprising at all. Everything should be >= the size of pointers, so 64-bit long integers.

> Now if you were referring to the implementation class snippets I left there, to be honest they were a last-minute addition and I mistakenly uses arrays there. The same problem also applies with tensors implementation if they work with a single ByteBuffer.

Well, I still think they should work with Java arrays and buffers, just not everything is going to fit. How do you see the story about interop with other libraries happening, especially for arrays that don't fit?

**Comment by Craigacp** [comment]
@karllessard, cool, if people want the unboxed one you can always leave the method there. I'll ask around about improvements to box elimination.

@saudet What use cases do you have for a tensor with more than 2 billion elements in a single dimension? A vector of floats that size is at least 8GB, and any higher dimensional tensors would have commensurate storage increases.

**Comment by saudet** [comment]
`numpy.ndarray.flatten()` gives you that on that 1000x2000x2000 tensor, and NumPy has absolutely no issues with that. Let's check how much RAM the largest machine has these days. 

> Using 2048 GB CDIMM features yields a maximum of 16 TB per node

https://www-01.ibm.com/common/ssi/rep_ca/6/877/ENUSZG18-0086/

I think we have a winner here. And 8 GB is 0.05% of its total RAM. The way you guys think about these things are making me seriously reconsider the future of Java in general...

**Comment by Craigacp** [comment]
I think that current ML has no need for that flatten operation, apart from serialisation which we should solve another way. The largest public models don't have a single dimension which has more than 2^31 elements (nor any single tensor which has that many elements), and given how many trainable parameters that is it's unlikely we'll get there soon. Anyway, the proposed API allows a user to slice up a tensor into multiple chunks and access them via normal Java data structures that way. The current TF API is also limited as there isn't a good way of expressing large arrays in the Java language, and we can't change that so easily.

BTW I've got a few servers downstairs with 3TB of RAM, and I've not needed to work around Java's array size limitations for any of the ML work I've been doing. The JVM has GC's which scale up to 16TB, but this support isn't in Java 8 which is our target platform, and things that are likely to make us bump the minimum target platform (e.g. vectorisation or value types) are also likely to change how we design the API (as we'll have specialised generics).

**Comment by karllessard** [comment]
After talking to a few data scientists here, it seems that flattening a tensor might increase in popularity with the arrival of some new parallel multi-tasking technics. That extra `L` might pay off in the long run, so let's make those indices 64-bit as well. Praise be!

@saudet for library interoperability, I think if a library wants to play with TensorFlow tensors, it must include a dependency to TensorFlow artifacts. There is no guarantee how TF will organize its tensor data internally (think of string tensors, for example) so it is not as simple as passing around a pointer to a native buffer. The TensorFlow artifacts will provide the required logic to manipulate this data. 

In case it is not possible to add this dependency, it is always possible to serialize/deserialize that data to the JVM space using, for example, I/O streams.

**Comment by karllessard** [comment]
@Craigacp just to sync up with you, do you think we should still dig a little bit more before deciding to go with 64-bits indices? Apart avoiding the `L` suffix, do you see any other advantages to stay with 32-bits integers?

**Comment by Craigacp** [comment]
I don't think there is much of an issue with using longs instead of ints. It does mean there will be casting everywhere when you interact with the indices in Java, which is annoying, but not dealbreaking (as the aim is to try and avoid doing that as much as possible). We could mitigate that by adding two methods that convert long arrays into int arrays and vice versa, though the long->int one will need to check for overflow and throw an exception.

It does feel weird to extract things into a `double[]` using long indices, but I suppose it's possible to extract a chunk that will fit into a Java array but needs the extra room of a long to specify the index. It should have a well defined (runtime) exception thrown if the indices specify something larger than a Java array, and maybe a static helper method somewhere that validates that the specified indices are small enough to fit in a Java array.

**Comment by saudet** [comment]
The current Java API of TF **does** use `long`, not `int`:
> static Shape make(long firstDimensionSize, long... otherDimensionSizes)                   
                 
https://www.tensorflow.org/api_docs/java/reference/org/tensorflow/Shape.html

> static Tensor<Float> create(long[] shape, FloatBuffer data)

https://www.tensorflow.org/api_docs/java/reference/org/tensorflow/Tensor

As for Java not supporting 64-bit indices, please do put pressure on Project Panama for us @Craigacp :)

@karllessard TensorFlow does offer guarantees on how the data is represented in memory, even for TF_STRING, as per the C API:
>```
> // --------------------------------------------------------------------------
> // TF_Tensor holds a multi-dimensional array of elements of a single data type.
> // For all types other than TF_STRING, the data buffer stores elements
> // in row major order.  E.g. if data is treated as a vector of TF_DataType:
> //
> //   element 0:   index (0, ..., 0)
> //   element 1:   index (0, ..., 1)
> //   ...
> //
> // The format for TF_STRING tensors is:
> //   start_offset: array[uint64]
> //   data:         byte[...]
> //
> //   The string length (as a varint), followed by the contents of the string
> //   is encoded at data[start_offset[i]]]. TF_StringEncode and TF_StringDecode
> //   facilitate this encoding.
> ```

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/tf_tensor.h#L47

If we need to import the whole of TensorFlow just to use this API though, I think that will severely limit its use cases. TensorFlow would be in a good position to become some sort of standard for n-dimensional arrays, but not if that means downloading 100 MB JAR files. In any case, if OpenJDK doesn't decide to ship something either via Project Panama, I suppose Arrow will eventually fill that role, and it supports CUDA as well, but it bundles LLVM, which is not so small, that's annoying. Anyway, we can most likely map that TF string format using Arrow too:
https://arrow.apache.org/docs/memory_layout.html

**Comment by Craigacp** [comment]
@saudet Panama isn't going to change the Java array spec, I don't think it plans to change the Java language itself, however there is an effort to change Java arrays called Arrays 2.0, but that's on the backburner at the moment while bigger projects like Panama and Valhalla are running.

**Comment by karllessard** [comment]
> @karllessard TensorFlow does offer guarantees on how the data is represented in memory, even for TF_STRING, as per the C API:

@saudet , yes, it is defined by the C API, but how much a Java library outside the TensorFlow ecosystem should know about the internal details of TF? For example, that TF_STRING contract you sent is brand new and not even in prod yet. Right now it's a different format in the C API, including a `vararg` attribute before each string, and even TF Lite (used in Android) use a different format as well. So the other libraries working directly in the tensor memory will have to keep track of changes in different TF releases and adapt their code as well. I don't think it is the right thing to do and it should be the responsibility of TensorFlow (hence this SIG) to provide tools that encapsulate the logic to manipulate tensor buffers in Java.

Now the `tensorflow-io` library proposed (or whatever name we pick for it) is a self-contained library that does not depend on the TensorFlow core. Right now, it just contain the API and what I called the `Standard NdArrays` implementations but I think we can include the `Tensor` implementations as well, at least the part that does not interact with the C API directly. So the library will remain small in size and nothing would prevent us to pass along `NdArray` and `Tensor` objects to other libraries depending only on this artifact. What do you think?

**Comment by saudet** [comment]
I'm sure the memory layout for TF_STRING respects the format described there, but yeah it looks like TensorFlow Lite deviates. There is a plan to unify all this though, but it sounds like they want to go back to something like arrays of `std::string`: https://github.com/tensorflow/community/blob/master/rfcs/20190411-string-unification.md  Anyway, the whole point of frameworks like Arrow is that pretty much all libraries have well defined memory layouts, including TensorFlow, usually.

Yes, I think a small library like that makes sense, but thinking a bit more about it, I'm not sure if it's really that practical w.r.t TensorFlow itself. In any case, the most important thing is being able to share memory buffers with other libraries. Other things will fall in place once that is settled. If we're not willing to share memory buffers, I don't personally feel it's worth spending too much time on this for now though.

**Comment by karllessard** [comment]
> I'm sure the memory layout for TF_STRING respects the format described there

In the core, yes, but for some reasons, when the tensor is created through the C API, the initial data must be provided in a different format. It's explained in the RFC you were referring too. But anyway, I guess it is not too important at this point.

>  If we're not willing to share memory buffers, I don't personally feel it's worth spending too much time on this for now though.

Sounds good. The light-weight library is already planned in the current proposal so let's just keep in mind that it would be nice to move the `Tensor` manipulators in it as well if it's not too much trouble, I'll mention it in the document.

**Comment by saudet** [comment]
> In the core, yes, but for some reasons, when the tensor is created through the C API, the initial data must be provided in a different format. It's explained in the RFC you were referring too. But anyway, I guess it is not too important at this point.

I must be blind, can you point me to that passage? This code works just fine:

https://github.com/eclipse/deeplearning4j/blob/68ea5f3688be9045cac3c06b1828b21262b22903/nd4j/nd4j-tensorflow/src/main/java/org/nd4j/tensorflow/conversion/TensorflowConversion.java#L154-L177

Maybe you are referring to the internal conversion to `std::string[]`? Yes, that's problematic, but it's not something we can control at the C API level. We would need to dig into the "unstable" C++ API...

> Sounds good. The light-weight library is already planned in the current proposal so let's just keep in mind that it would be nice to move the Tensor manipulators in it as well if it's not too much trouble, I'll mention it in the document.

Well, think of this way. I was looking at the TensorFlow I/O libraries, and they have one for Arrow, but look at that warning:
> NOTE: The entire DataFrame will be serialized to the Dataset and is not recommended for use with large amounts of data

https://github.com/tensorflow/io/blob/master/tensorflow_io/arrow/README.md

That sounds kind of limiting. We should find a way to do something that doesn't end up like that... but then again I'm starting to get the impression that a lot data gets copied around in TF itself anyway.

**Comment by karllessard** [comment]
> Maybe you are referring to the internal conversion to `std::string[]`? Yes, that's problematic, but it's not something we can control at the C API level. We would need to dig into the "unstable" C++ API...

Yeah sorry for the confusion again, I thought you were initially referring to the new format Google is working on right now, which might slightly differ from the current one in C API (i.e. the one used in your code snippet that adds a `varint` before each value). And yes, for the C++ string arrays, that won't cross the C API so we won't have to deal with it.

> That sounds kind of limiting. We should find a way to do something that doesn't end up like that... but then again I'm starting to get the impression that a lot data gets copied around in TF itself anyway.

I'm under that impression too. For example, I think when you create a constant in TF, even if you provide a fully initialized tensor, the core will make a copy of its data so it remains immutable (which is good but could be memory consuming for large constants).

**Pull request merged**
